# renovate needs to know that the changes it makes are building and tests pass
# before it creates PRs. so have the renovate branches build on pushed changes
# Use something like this but change the steps to suit your build
name: Build and Test
on:
    push:
        branches:
            - "renovate/**"
    pull_request:
        branches:
            - main
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
              with:
                  node-version: "18"
            - run: yarn
            - run: yarn test
            - run: yarn build
